- project:
    check:
      jobs:
        - f34-clang-asan-ubsan:
            pre-run: ci/pre.yaml
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/CESNET/libnetconf2
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/2021-10-08
              - name: github/rollbear/trompeloeil
                override-checkout: v41
              - name: CzechLight/libyang-cpp
        - f34-clang-tsan:
            pre-run: ci/pre.yaml
            required-projects: *projects
