- hosts: all
  tasks:
    - name: install libssh-debuginfo
      command: 'dnf debuginfo-install -y libssh'
      become: true

    - name: install curl
      package:
        name: libcurl-devel
        state: present
      become: true
